services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cloud-server
    ports:
      - "8808:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./storage:/app/storage
      - ./server/server.json:/app/server.json:ro
    restart: unless-stopped
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Ensure the container runs with the correct user ID
    user: "1000:1000"

  webclient:
    build:
      context: .
      dockerfile: webclient/Dockerfile
    container_name: cloud-webclient
    ports:
      - "8818:8008"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cloud_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage

networks:
  cloud-network:
    driver: bridge

