version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cloud-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - server_data:/data
      - ./server/server.json:/app/server.json:ro
    restart: unless-stopped
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webclient:
    build:
      context: .
      dockerfile: webclient/Dockerfile
    container_name: cloud-webclient
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  server_data:
    driver: local

networks:
  cloud-network:
    driver: bridge
