name: Deploy Cloud Storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build server image
      run: |
        docker build -f server/Dockerfile -t cloud-server:latest .

    - name: Build webclient image
      run: |
        docker build -f webclient/Dockerfile -t cloud-webclient:latest .

    - name: Run tests (if available)
      run: |
        # Add test commands here when tests are implemented
        echo "Tests would run here"

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-server:latest

    - name: Build and push webclient image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: webclient/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-webclient:latest

    - name: Copy docker-compose to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: docker-compose.yml
        target: /root/vizn3rcloud/

    - name: Deploy to server (SSH)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Pull latest images
          cd /root/vizn3rcloud
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cloud-server:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cloud-webclient:latest

          # Stop and remove old containers
          docker compose down

          # Start new containers
          docker compose up -d
