name: Deploy Cloud Storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to server (SSH)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Update repository and build local images
          cd /root/vizn3rcloud
          git pull origin main

          # Build server image
          docker build -f server/Dockerfile -t cloud-server:latest .

          # Build webclient image
          docker build -f webclient/Dockerfile -t cloud-webclient:latest .

          # Stop and remove old containers
          docker compose down

          # Start new containers
          docker compose up -d
